// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmhxh6hvd6l8khoA8SVHeakeFU96FTEs4',
    appId: '1:298112734306:android:010f980c2ab8faf7cd2d3b',
    messagingSenderId: '298112734306',
    projectId: 'drunken-sailor-f6905',
    storageBucket: 'drunken-sailor-f6905.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlFum32RB9iWBjtfP9NjuzRUGcGJVzBuE',
    appId: '1:298112734306:ios:1b51df1abe263848cd2d3b',
    messagingSenderId: '298112734306',
    projectId: 'drunken-sailor-f6905',
    storageBucket: 'drunken-sailor-f6905.firebasestorage.app',
    iosBundleId: 'com.example.drunkenSailor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlFum32RB9iWBjtfP9NjuzRUGcGJVzBuE',
    appId: '1:298112734306:ios:1b51df1abe263848cd2d3b',
    messagingSenderId: '298112734306',
    projectId: 'drunken-sailor-f6905',
    storageBucket: 'drunken-sailor-f6905.firebasestorage.app',
    iosBundleId: 'com.example.drunkenSailor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjtjY_YIKTgOGsk2Mn66cMuAoz3D1sJ8g',
    appId: '1:298112734306:web:b1ca3df387b97636cd2d3b',
    messagingSenderId: '298112734306',
    projectId: 'drunken-sailor-f6905',
    authDomain: 'drunken-sailor-f6905.firebaseapp.com',
    storageBucket: 'drunken-sailor-f6905.firebasestorage.app',
    measurementId: 'G-PGWRKSTDTW',
  );
}
